/* Interleaving Arrays
Create a function, that accepts an arbitrary number of arrays and returns a single array generated by alternately 
appending elements from the passed in arguments. If one of them is shorter than the others, the result should be padded 
with empty elements.

Examples:
interleave([1, 2, 3], ["c", "d", "e"]) === [1, "c", 2, "d", 3, "e"]
interleave([1, 2, 3], [4, 5]) === [1, 4, 2, 5, 3, null]
interleave([1, 2, 3], [4, 5, 6], [7, 8, 9]) === [1, 4, 7, 2, 5, 8, 3, 6, 9]
interleave([]) === []
*/

const interleave = (...arr) => {
    const res = [];
    for (let i = 0; i < Math.max(...arr.map(e => e.length)); i++) {
        for (let j = 0; j < arr.length;j++) {
            res.push(arr[j][i] !== undefined ? arr[j][i] : null);
        }
    }
    return res;
}

console.log(interleave([1, 2, 3], ["c", "d", "e"])) // [1, "c", 2, "d", 3, "e"]
console.log(interleave([1, 2, 3], [4, 5])) // [1, 4, 2, 5, 3, null]
console.log(interleave([1, 2, 3], [4, 5, 6], [7, 8, 9])) // [1, 4, 7, 2, 5, 8, 3, 6, 9]
console.log(interleave([])) // []